# Generated by Django 5.2.4 on 2025-08-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default='Empty'),
        ),
    ]
